#!/bin/bash

echo "🔑 Creating New SSH Key Pair for EC2"
echo "===================================="
echo ""
echo "Follow these steps in AWS Console:"
echo ""
echo "1. Go to AWS Console → EC2 → Key Pairs"
echo "2. Click 'Create key pair'"
echo "3. Name: tourplan-booking-key"
echo "4. Key pair type: RSA"
echo "5. Private key file format: .pem"
echo "6. Click 'Create key pair'"
echo "7. Download and save the .pem file"
echo ""
echo "After creating the key pair:"
echo "8. Your instance is already stopped (good!)"
echo "9. Click Actions → Instance settings → Change key pair"
echo "10. Select your new key pair: tourplan-booking-key"
echo "11. Click 'Save'"
echo "12. Start the instance"
echo ""
echo "13. In PowerShell, run:"
echo "    ssh -i \"C:\\Users\\YourName\\Downloads\\tourplan-booking-key.pem\" ec2-user@13.210.224.119"
echo ""
echo "Note: Replace YourName with your actual Windows username"
